
/**
 * Each new term in the Fibonacci sequence is generated by adding the 
 * previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not 
 * exceed four million, find the sum of the even-valued terms
 * 
 * Abby Shah
 * 10/09/2015
 */
public class Problem2
{
   public static void main(String[] args)
   {
       System.out.println();
       int a = 0;
       int b = 1;
       int c = 0;
       int sum = 0;
       do
       {
           c = a + b;
           a = b;
           b = c;
           //System.out.println(c);
           
           if(c%2 == 0)
           {
               sum = sum + c;
           }
       }while(c < 3524578);
       
       System.out.println(sum);
   }
}
